In [1]:
import numpy as np

In [19]:
a = np.random.randint(1,1000, size=(10,10))
a

array([[516, 113, 570, 178, 166, 859,  17, 626, 417,  61],
       [770, 450, 793, 397,  95, 724,  49, 923, 811, 725],
       [337, 732, 675, 564, 227, 703, 594,  90, 514, 567],
       [ 62, 979, 542, 745, 619, 620, 856, 107, 145, 557],
       [538,  78,  17, 178, 205, 837,  38, 984, 622, 108],
       [636, 607, 168, 755,  64,  66, 247,  39, 742, 829],
       [153, 443, 144, 774,  59, 662, 682, 387, 673, 102],
       [236, 823, 972,   5, 576, 709, 752, 734, 979, 754],
       [326, 909, 144, 406, 763, 953, 454, 656, 931,  31],
       [512, 379, 874, 496, 413, 408, 878, 565, 936, 692]])

In [20]:

print(f"Minimum: {np.min(a)}, maximum: {np.max(a)}")

Minimum: 5, maximum: 984


In [28]:
print(f"Array has dim {np.ndim(a)}, shape {np.shape(a)}, size {np.size(a)}, and dtype {a.dtype}:")

Array has dim 2, shape (10, 10), size 100, and dtype int32:


In [38]:
arr = np.arange(1, 20,3)
ivers= arr[::-1]
print(f'the array from 1 to 20 with 7 elements : {arr} \n and the inverted array : {ivers}:' )

the array from 1 to 20 with 7 elements : [ 1  4  7 10 13 16 19] 
 and the inverted array : [19 16 13 10  7  4  1]:


In [59]:
null_v = np.zeros(10)

# Set the fifth value to 1
null_v[4] = 1
null_v

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [63]:
swap_array=a[0], a[1] = a[1].copy(), a[0].copy()
swap_array

(array([770, 450, 793, 397,  95, 724,  49, 923, 811, 725]),
 array([516, 113, 570, 178, 166, 859,  17, 626, 417,  61]))